version: "2"

services:
  fpm:
    # build: "./fpm"
    image: joelhy/fpm
    volumes:
      - ./app:/var/www/app

  nginx:
    build: "./nginx"
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./app:/var/www/app
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled

  mysql:
    # mariadb use less meory than mysql: 258 MB vs. 429.2 MB
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - mysql-data:/var/lib/mysql

  memcached:
    image: memcached

  redis:
    image: redis
    volumes:
      - redis-data:/var/lib/redis

volumes:
  redis-data:
    driver: local
  mysql-data:
    driver: local
